"""Updated scheme table

Revision ID: 2c9f9b35afa4
Revises: bc0f54386814
Create Date: 2024-07-26 12:56:13.978620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c9f9b35afa4'
down_revision: Union[str, None] = 'bc0f54386814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheme', sa.Column('SchemeAmount', sa.Integer(), nullable=False))
    op.add_column('scheme', sa.Column('SchemeCover', sa.Integer(), nullable=False))
    op.add_column('scheme', sa.Column('SchemeTenure', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheme', 'SchemeTenure')
    op.drop_column('scheme', 'SchemeCover')
    op.drop_column('scheme', 'SchemeAmount')
    # ### end Alembic commands ###
