"""Overall database for insurance app

Revision ID: bc0f54386814
Revises: fffaa58cfd03
Create Date: 2024-07-25 12:44:30.638274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc0f54386814'
down_revision: Union[str, None] = 'fffaa58cfd03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insuranceplan',
    sa.Column('PlanID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PlanName', sa.String(length=100), nullable=False),
    sa.Column('PlanDetails', sa.Text(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('PlanID')
    )
    op.create_index(op.f('ix_insuranceplan_PlanID'), 'insuranceplan', ['PlanID'], unique=False)
    op.create_table('scheme',
    sa.Column('SchemeID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SchemeName', sa.String(length=100), nullable=False),
    sa.Column('SchemeDetails', sa.Text(), nullable=False),
    sa.Column('PlanID', sa.Integer(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['PlanID'], ['insuranceplan.PlanID'], ),
    sa.PrimaryKeyConstraint('SchemeID')
    )
    op.create_index(op.f('ix_scheme_SchemeID'), 'scheme', ['SchemeID'], unique=False)
    op.create_table('employeescheme',
    sa.Column('EmployeeSchemeID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EmployeeID', sa.Integer(), nullable=False),
    sa.Column('SchemeID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['EmployeeID'], ['employee.EmployeeID'], ),
    sa.ForeignKeyConstraint(['SchemeID'], ['scheme.SchemeID'], ),
    sa.PrimaryKeyConstraint('EmployeeSchemeID')
    )
    op.create_index(op.f('ix_employeescheme_EmployeeSchemeID'), 'employeescheme', ['EmployeeSchemeID'], unique=False)
    op.create_table('policy',
    sa.Column('PolicyID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CustomerID', sa.Integer(), nullable=False),
    sa.Column('SchemeID', sa.Integer(), nullable=False),
    sa.Column('PolicyDetails', sa.Text(), nullable=False),
    sa.Column('Premium', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('DateIssued', sa.Date(), nullable=False),
    sa.Column('MaturityPeriod', sa.Integer(), nullable=False),
    sa.Column('PolicyLapseDate', sa.Date(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['CustomerID'], ['customer.CustomerID'], ),
    sa.ForeignKeyConstraint(['SchemeID'], ['scheme.SchemeID'], ),
    sa.PrimaryKeyConstraint('PolicyID')
    )
    op.create_index(op.f('ix_policy_PolicyID'), 'policy', ['PolicyID'], unique=False)
    op.create_table('commission',
    sa.Column('CommissionID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('AgentID', sa.Integer(), nullable=False),
    sa.Column('PolicyID', sa.Integer(), nullable=False),
    sa.Column('CommissionAmount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['AgentID'], ['insuranceagent.AgentID'], ),
    sa.ForeignKeyConstraint(['PolicyID'], ['policy.PolicyID'], ),
    sa.PrimaryKeyConstraint('CommissionID')
    )
    op.create_index(op.f('ix_commission_CommissionID'), 'commission', ['CommissionID'], unique=False)
    op.create_table('payment',
    sa.Column('PaymentID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CustomerID', sa.Integer(), nullable=False),
    sa.Column('PolicyID', sa.Integer(), nullable=False),
    sa.Column('Amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('PaymentDate', sa.Date(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['CustomerID'], ['customer.CustomerID'], ),
    sa.ForeignKeyConstraint(['PolicyID'], ['policy.PolicyID'], ),
    sa.PrimaryKeyConstraint('PaymentID')
    )
    op.create_index(op.f('ix_payment_PaymentID'), 'payment', ['PaymentID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_PaymentID'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_commission_CommissionID'), table_name='commission')
    op.drop_table('commission')
    op.drop_index(op.f('ix_policy_PolicyID'), table_name='policy')
    op.drop_table('policy')
    op.drop_index(op.f('ix_employeescheme_EmployeeSchemeID'), table_name='employeescheme')
    op.drop_table('employeescheme')
    op.drop_index(op.f('ix_scheme_SchemeID'), table_name='scheme')
    op.drop_table('scheme')
    op.drop_index(op.f('ix_insuranceplan_PlanID'), table_name='insuranceplan')
    op.drop_table('insuranceplan')
    # ### end Alembic commands ###
