"""Used backpropogation

Revision ID: fffaa58cfd03
Revises: 
Create Date: 2024-07-23 17:22:20.551290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fffaa58cfd03'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('AdminID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Username', sa.String(length=50), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.Column('FullName', sa.String(length=100), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('AdminID')
    )
    op.create_index(op.f('ix_admin_AdminID'), 'admin', ['AdminID'], unique=False)
    op.create_table('employee',
    sa.Column('EmployeeID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Username', sa.String(length=50), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.Column('FullName', sa.String(length=100), nullable=False),
    sa.Column('Role', sa.String(length=50), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('EmployeeID')
    )
    op.create_index(op.f('ix_employee_EmployeeID'), 'employee', ['EmployeeID'], unique=False)
    op.create_table('insuranceagent',
    sa.Column('AgentID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Username', sa.String(length=50), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.Column('FullName', sa.String(length=100), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('AgentID')
    )
    op.create_index(op.f('ix_insuranceagent_AgentID'), 'insuranceagent', ['AgentID'], unique=False)
    op.create_table('customer',
    sa.Column('CustomerID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FullName', sa.String(length=100), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.Column('Username', sa.String(length=50), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.Column('Phone', sa.String(length=15), nullable=False),
    sa.Column('DateOfBirth', sa.Date(), nullable=False),
    sa.Column('AgentID', sa.Integer(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['AgentID'], ['insuranceagent.AgentID'], ),
    sa.PrimaryKeyConstraint('CustomerID')
    )
    op.create_index(op.f('ix_customer_CustomerID'), 'customer', ['CustomerID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_CustomerID'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_insuranceagent_AgentID'), table_name='insuranceagent')
    op.drop_table('insuranceagent')
    op.drop_index(op.f('ix_employee_EmployeeID'), table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_admin_AdminID'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
